version: "3.9"
services:
  db:
    image: "postgres"
    restart: always
    ports: 
      - ${DATABASE_PORT}:${DATABASE_PORT}
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
    healthcheck:
      test: [
        "CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"
      ]
      start_period: 30s
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - ./db:/var/lib/postgresql/data
  app:
    build:
      context: .
      args:
        SECRET_KEY: ${SECRET_KEY}
    env_file: .env
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      DATABASE_HOST: db
      DATABASE_PORT: ${DATABASE_PORT}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"